---
# handlers file for roles/application_rm-containers
# roles/application_rm-containers/handlers/main.yml

# - name: Make sure Docker is running
  # service:
    # name: docker
    # state: started
  # tags: docker