language: java

#cache:
# directories:
# - "$HOME/.m2/repository"
# - "$HOME/.sonar/cache"

services:
 - docker

#before_install:
# - docker pull postgres:9.6
# - docker run -d -p 5432:5432 postgres

script:
 - mvn dependency:go-offline clean verify
 - docker build -t db-changelog-job ./sample-application-db-changelog-job/
 - docker build -t http-api-server ./sample-application-http-api-server/

notifications:
 email:
   on_failure: always

deploy:
 provider: script
# script: ssh -i /tmp/travis_deploy_rsa $USER@$SERVER" sudo docker pull $IMAGE_NAME:$TAG && sudo docker rm -f app || true && sudo docker run -d --network net -p 80:8080 --name app $IMAGE_NAME:$TAG"
 script: docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD && docker tag db-changelog-job tbgfr/db-changelog-job:develop && docker push tbgfr/db-changelog-job:develop && docker tag http-api-server tbgfr/http-api-server:develop && docker push tbgfr/http-api-server:develop 
 on:
   branch: develop