---
# tasks file for roles/common
# roles/common/tasks/main.yml

- name: Close all ports
  iptables:
    action: insert
    destination_port: first:last
    policy: DROP
    protocol: tcp

- name: Open port 80 (HTTP)
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true
    
- name: Open port 22 (SSH)
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Open port 443 (HTTPS)
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
    immediate: true
        
# - name: Install device-mapper-persistent-data
  # yum:
    # name: device-mapper-persistent-data
    # state: latest
        
# - name: Install lvm2
  # yum:
    # name: lvm2
    # state: latest

# - name: Add Docker stable repository
  # yum_repository:
    # name: docker-ce
    # description: Docker CE Stable - $basearch
    # baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    # state: present
    # enabled: yes
    # gpgcheck: yes
    # gpgkey: https://download.docker.com/linux/centos/gpg

# - name: Install Docker
  # yum:
    # name: docker-ce
    # state: present