
- hosts: all
  gather_facts: false
  become: yes
  
  tasks:
  
    - include_role:
        name: application_rm-containers
        
    - include_role:
        name: application_rm-images